//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet_summaries
    {
        public int Id { get; set; }
        public Nullable<int> Timesheet_id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string Rate { get; set; }
        public string Enitial { get; set; }
        public Nullable<double> Total_hours { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Rating_by_client { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Timesheet Timesheet { get; set; }
    }
}
